
DROP INDEX i_genre;
DROP INDEX i_movie_tag;
DROP INDEX i_actorName;

DROP TABLE USER_TAG;
DROP TABLE MOVIE_TAG;
DROP TABLE TAG;
DROP TABLE GENRE;
DROP TABLE DIRECTORS;
DROP TABLE COUNTRY;
DROP TABLE ACTORS;
DROP TABLE MOVIE;
